# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MapTalk' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MapTalk

  pod 'SwiftLint'
  pod 'FBSDKLoginKit'
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Kingfisher', '~> 4.0'
  pod 'RAMAnimatedTabBarController'
  pod 'IQKeyboardManagerSwift'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'NotificationBannerSwift'
  pod 'KeychainAccess'
  pod 'SVProgressHUD'



#  pod 'GoogleMaps'
#  pod 'GooglePlaces'
#  pod 'SDWebImage'
#  pod 'RAMAnimatedTabBarController'
#  pod 'FBSDKCoreKit'
#  pod 'FacebookCore'
#  pod 'FacebookLogin'
end
